[config]
schemaVersion = "0.0.1"


[package]
namespace = "PonyWarrior"
name = "PonyQOL2"
versionNumber = "0.3.1"
description = "Make your life easier with pony's quality of life 2, the returning mod from Hades 1."
websiteUrl = "https://github.com/PonyWarrior/PonyQOL2"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-DemonDaemon = "1.0.0"
SGG_Modding-ModUtil = "3.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
